.travis.yml, galaxy.yml, molecule/__ihs-v85/converge.yml, molecule/__ihs-v90/converge.yml, molecule/iim-191-centos-8/converge.yml, molecule/iim-191-centos-8/molecule.yml, roles/iim/README.md, roles/iim/defaults/main.yml, roles/iim/tasks/darwin.yml, roles/iim/tasks/linux_common.yml, roles/iim/tasks/windows.yml, roles/iim/vars/darwin.yml, roles/iim/vars/debian.yml, roles/iim/vars/redhat.yml, roles/iim/vars/windows.yml, scripts/downloadInstaller.sh
- Remove duplicate scenario from travis
- Add option to download iim installer zip from server
- Update molecule to use download option instead of messy copy script
- Update vars to work with both copy/download (by adding iim_installer_path)
- Add download_url to ihs molecule tests to use download
- Fix some obvious windows bugs e.g. copy instead of win_copy - should be tested in future
Replaces original PR: https://github.com/IBM/spm-middleware/pull/20
=> IIM - Optional Download ( alternative to copy )

.github/workflows/main.yml, galaxy.yml, roles/db2/tasks/prereqs.yml
`libstdc++` installed as dependency of `gcc-c++`
`gcc-c++` installs an older `libstdc++` version, newer version is not compatible with `gcc-c++` which is required for db2 installation
=> Remove libstdc++ from prereqs

galaxy.yml, roles/liberty/files/AppServer.properties, roles/weblogic/defaults/main.yml, roles/websphere/templates/AppServer.properties.j2
These changes will be made again shortly once we're ready to merge all the unencrypted-password related PRs accross our bootstrap repos and our spm-deployments repo.
For revert to how it was previously.
=> revert till ready to merge all

galaxy.yml, roles/liberty/files/AppServer.properties, roles/weblogic/defaults/main.yml, roles/websphere/templates/AppServer.properties.j2
These changes will be merged along with the changes to spm_deployment to use plaintext passwords for websphere/weblogic/liberty that will then be encrypted on the fly during deployment (rather than starting with an encrypted password that is always encrypted the same). The reason is that shipping the same encrypted pass always was considered a vulnerability.
See ticket
=> Change the appserver passwords to plaintext

galaxy.yml, molecule/__websphere-v90/converge.yml, roles/liberty/defaults/main.yml, roles/liberty/tasks/main.yml, roles/liberty/templates/AppServer.properties.j2, roles/weblogic/defaults/main.yml, roles/websphere/defaults/main.yml, roles/websphere/tasks/main.yml, roles/websphere/templates/AppServer.properties.j2
- update galaxy version
- use placeholder passwords in default vars files
- change AppServer.properties to template in liberty role
- create security_username and security_password vars
=> WAS - use var for security password

.github/workflows/main.yml, galaxy.yml, roles/iim/tasks/centos.yml, roles/iim/tasks/debian.yml, roles/iim/tasks/main.yml, roles/iim/tasks/redhat.yml, roles/ohs/vars/v12.1.3.0.200412.yml, roles/ohs/vars/v12.2.1.4.210324.yml, roles/weblogic/defaults/main.yml
https://github.com/merative/spm-middleware/tree/moveJDK
Per the story we need to move the  java JDKs used by ohs and weblogic to the WLS folder (both, confirmed by sian). This PR is to point our collection at the new location.
1) Point collection at new JDK location and increment galaxy version to publish collection
2) Remove includes module as this is failing our molecule with a deprecation error.
Ran molecule tests in devenv as instructed here:
https://galaxy.ansible.com/ui/repo/published/merative/spm_middleware/docs/
Also GH actions will do the same for this PR.
=> move java installer for ohs/IHS

.github/workflows/main.yml, galaxy.yml, molecule/__liberty21/converge.yml, molecule/__liberty21/verify.yml, molecule/liberty-jdk21-rockylinux8/molecule.yml, roles/liberty/tasks/main.yml, roles/liberty/vars/v23.0.0.12-JDK21.yml
Add JDK21 support on 23.0.0.12. This is for a POC project.
Add a new var file: 23.0.0.12-JDK21.yml .
To use this combination, need to set liberty_version to 23.0.0.12-JDK21 in parent playbook
=> Add JDK21 for liberty

galaxy.yml, molecule/__oracle-v19c/verify.yml, roles/oracle/defaults/main.yml, roles/oracle/tasks/main.yml
to make oracle auto restart after machine reboot
test passed here: https://github.com/merative/spm-middleware/actions/runs/8661573609
=> Orautostart

galaxy.yml, roles/ihs/vars/v9.0.5.19.yml, roles/websphere/vars/v9.0.5.19.yml
Update Java version for IHS & WAS.  
Update to use FP20 as suggested here - https://www.ibm.com/support/pages/node/317689#W9J8
Molecule test for WAS & IHS passed with new Java Version
=> Update Java version for IHS & WAS

.devcontainer/devcontainer.json, galaxy.yml, molecule/__liberty/converge.yml, molecule/__liberty17/converge.yml, molecule/__liberty21/converge.yml, roles/liberty/defaults/main.yml, roles/liberty/vars/v24.0.0.3-JDK17.yml, roles/liberty/vars/v24.0.0.3-JDK21.yml, roles/liberty/vars/v24.0.0.3.yml
add WLP 24.0.0.3, supported with JAVA 8, 17, 21
=> add wlp 24.0.0.3

ci-requirements.txt, galaxy.yml, requirements.txt
Hardcode Requests package version
This is due to the recent update to this package which breaks running the molecule tests.
[requestsissue.txt](https://github.com/merative/spm-middleware/files/15388041/requestsissue.txt)
See https://github.com/psf/requests/issues/6707
=> Hardcode Requests package version

molecule/__ihs-v85/converge.yml, molecule/__websphere-v85/converge.yml, roles/ihs/vars/v8.5.5.25.yml, roles/websphere/vars/v8.5.5.25.yml
Update v8 WebSphere and IBM HTTP Server to v8.5.5.25 - new yaml files 
Update READMEs
Update Molecule tests
Update galaxy file
=> Update v8 WAS & IHS to 8.5.5.25

galaxy.yml, molecule/__weblogic-v14.1/converge.yml, molecule/__weblogic-v14.1/verify.yml, roles/weblogic/README.md, roles/weblogic/defaults/main.yml, roles/weblogic/vars/v14.1.1.0.240628.yml
New WLS 14.1.1.0.240628 yaml file
Update Molecule tests
Update README
Update Galaxy.xml
=> Update to WLS 14.1.1.0.240628

galaxy.yml, molecule/__liberty/converge.yml, roles/liberty/README.md, roles/liberty/defaults/main.yml, roles/liberty/vars/v24.0.0.9.yml
Update WebSphere Liberty (java 8) to v24.0.0.9 - new yaml file Update READMEs
Update Molecule tests
Update galaxy file
=> Update WebSphere Liberty (java 8) to v24.0.0.9

galaxy.yml, molecule/__liberty17/converge.yml, molecule/__liberty21/converge.yml, roles/liberty/vars/v24.0.0.9-JDK17.yml, roles/liberty/vars/v24.0.0.9-JDK21.yml
Update WebSphere Liberty (java 17 & java 21) to v24.0.0.9 - new yaml file Update Molecule tests
Update galaxy file
=> Update WebSphere Liberty (java 17 & 21) to v24.0.0.9

galaxy.yml, roles/ohs/tasks/main.yml, roles/ohs/vars/v12.2.1.4.0.yml
I am trying manually work around https://github.com/spm-devops/transformers/issues/1327 - until this is fixed.
On a VM i can manually install all the required pieces i.e. OHS Base
OHS 19c Upgrade
OHS 19c latest patches
However manually it is more difficult to complete the OHS config for Curam -  as this has a number of steps including creating SSL certs etc.
To help this I have created a YAML file to just install the Base version of OHS.  This will mean when i choose this version when deploying a VM - it will in stall the base and configure OHS for use with Curam..  I can then manually install the 19c upgrade and latest patches - and OHS should be automatically configured for me (from the base install)
This changeset has a YAML file which just installs the Base version (commented out the …
=> OHS Base YAML install file

roles/ohs/tasks/main.yml
OHS Base Install - Improve checks on Patch OHS when there are no patches
Failed when deploying VM in Jenkins.. despite all molecule tests passing when submitting initial change
https://spmdevops-team-apollo.jenkins.commops.merative.com/job/DevOps-Jenkins-ProvisionerWrapper/1115/
Added in improved checks to determine of OHS should be patched based off contents in yaml file
=> OHS Base Install - Improve checks on Patch OHS when there are no patches

galaxy.yml, molecule/__ohs-v12.2.1.4/converge.yml, molecule/__ohs-v12.2.1.4/verify.yml, roles/ohs/README.md, roles/ohs/defaults/main.yml, roles/ohs/tasks/19cupgrade.yml, roles/ohs/tasks/main.yml, roles/ohs/tasks/patch.yml, roles/ohs/vars/v12.2.1.4.240906.yml
Up to now we have been installing the 12c Client for the Oracle HTTP Server.  This is already or about to go out of support.  So we need to switch to the supported version i.e. 19C Client..
Initially a ticket was created for this work - https://github.com/spm-devops/transformers/issues/1327
But the code deliever in this PR should cover what is required.
New Oracle 19c Upgrade Yaml file
Updates to existing main & patch yaml to accomodate changes in the Upgrade
Latest 19c fixpacks for patching
Updated molecule tests
Update README
Update Galaxy.yml
All molecule tests passing locally for latest 19c patches and for last 12c patch
=> Update OHS code to upgrade to 19c Client

galaxy.yml, roles/ohs/vars/v12.2.1.4.240906.yml
**_Summary_**
When deploying OHS with DB Client 19c version we saw an issue logging into Curam post deployment.
This meant there was issues decoding content and ultimately resources (e.g. css files) not being downloaded and impacting the visual and usability of Curam.
**_Errors_**
From investigation we found errors in the logs
`[2024-12-04T15:29:26.6689+00:00] [OHS] [ERROR:32] [OH99999] [weblogic] [client_id: 172.32.0.6] [host_id: mfohstest] [host_addr: 10.0.0.247] [pid: 687368] [tid: 140379588388608] [user: root] [ecid: 006A7Dimq5vFGB05zzG7yW002bo8000007] [rid: 0] [VirtualHost: mfohstest.internal.cloudapp.net:443] ap_proxy: trying GET /Curam/CDEJ/css/custom.css at backend host 10.0.0.247/7002, client 172.32.0.6/49798, total tries 1; got exception 'PROTOCOL_ERROR [line 1010 of URL.cpp]: …
=> Update 19c patch var file - add in new patch/fix zip

.github/workflows/main.yml, galaxy.yml, molecule/db21211/converge.yml, molecule/db21211/molecule.yml, molecule/db21211/verify.yml, roles/db2/README.md, roles/db2/vars/v12.1.1.0.yml
DB2 12.1.1 Fixpack Updates
New Fiaxpack released for DB2 12.1
YAML file
New db21211 role
Updated ReadME
=> DB2 12.1.1 Fixpack Updates

.github/workflows/main.yml, galaxy.yml, molecule/weblogic-rockylinux9/molecule.yml, roles/weblogic/meta/main.yml, roles/weblogic/vars/os_9.yml
With RHEL 9 being supported in 8.2.0.0 - we need to ensure that it can deploy correctly.
An initial test on a RHEL9 VM with Weblogic failed due to
`TASK [merative.spm_middleware.weblogic : Include based on OS version variables] ***
fatal: [mfwlsorarhel9]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access 'os_9.yml'\nSearched in:\n\t/home/jenkins/remoting/workspace/DevOps-Jenkins-ProvisionerWrapper/playbooks/install_middleware/ansible_collections/merative/spm_middleware/roles/weblogic/vars/os_9.yml\n\t/home/jenkins/remoting/workspace/DevOps-Jenkins-ProvisionerWrapper/playbooks/install_middleware/ansible_collections/merative/spm_middleware/roles/weblogic/os_9.yml\n\t/home/jenkins/remoting/workspace/DevOps-Jenkins-Provisi …
=> Add WebLogic support for RHEL 9

galaxy.yml, molecule/__ihs-v85/converge.yml, molecule/__ihs-v90/converge.yml, molecule/__liberty/converge.yml, molecule/__liberty21/converge.yml, molecule/__websphere-v85/converge.yml, molecule/__websphere-v90/converge.yml, molecule/iim-191-rockylinux8/converge.yml, molecule/iim-191-rockylinux9/converge.yml, roles/ihs/README.md, roles/ihs/defaults/main.yml, roles/ihs/vars/v8.5.5.27.yml, roles/ihs/vars/v9.0.5.23.yml, roles/iim/README.md, roles/iim/defaults/main.yml, roles/liberty/defaults/main.yml, roles/liberty/vars/v25.0.0.3-JDK21.yml, roles/liberty/vars/v25.0.0.3.yml, roles/websphere/README.md, roles/websphere/defaults/main.yml, roles/websphere/vars/v8.5.5.27.yml, roles/websphere/vars/v9.0.5.23.yml
Update to latest IBM Installation Manager - 1.9.301 
Update WebSphere and IBM HTTP Server to v9.0.5.23 - new yaml files 
Update WebSphere Liberty to v25.0.0.3 - new yaml files (Java8 and Java21) 
Update WebSphere and IBM HTTP Server with new V8.5.5 version - v8.5.5.27 - new yaml files 
Update READMEs
Update Molecule Tests
Update Galaxy file
=> Update IBM Middleware to latest Fixpacks

.github/workflows/main.yml, galaxy.yml, molecule/__weblogic-v14.1.2/converge.yml, molecule/__weblogic-v14.1.2/verify.yml, molecule/weblogic-1412-rockylinux8/molecule.yml, molecule/weblogic-1412-rockylinux9/molecule.yml, roles/weblogic/README.md, roles/weblogic/vars/v14.1.2.0.250324.yml
Creating and introducing YAML files for Weblogic 14.1.2 (which uses Java21)
- New YAML file for 14.1.2 (including new base installer, latest WLS patch, and latest Java21 JDK)
- Added in molecule tests for WLS 14.1.2 on RHEL8 and RHEL9
- Updated ReadME
- Updated Galaxy file
Molecule tests have passed locally for RHEL 8 and RHEL 9.. No issues with the install and patching
=> Support for WLS 14.1.2
